n1 = (input("Digite algo : "))
print("O tipo primitivo desse valor é {}".format(type(n1)))
print("Só tem espaços {}" .format(n1.isspace()))
print('É um número ? {} ?'.format(n1.isnumeric()))
print('É alefabetico ? {}'.format(n1.isalpha()))
print('É alfanumérico? {}'.format(n1.isalnum()))
print('Está em maiúsculaS? {}'.format(n1.isupper()))
print('Está em minúsculas? {}'.format(n1.islower()))
print('Está capitalizada? {}'.format())