n = int(input('Digite um número para ver sua tabuada: '))
i = '='
print(i*25)
print('{} * 1 = {}'.format((n),(n*1)))
print('{} * 2 = {}'.format((n),(n*2)))
print('{} * 3 = {}'.format((n),(n*3)))
print('{} * 4 = {}'.format((n),(n*4)))
print('{} * 5 = {}'.format((n),(n*5)))
print('{} * 6 = {}'.format((n),(n*6)))
print('{} * 7 = {}'.format((n),(n*7)))
print('{} * 8 = {}'.format((n),(n*8)))
print('{} * 9 = {}'.format((n),(n*9)))
print('{} * 10 = {}'.format((n),(n*10)))
print(i*25)
